apiVersion: v1
kind: Service
metadata:
  name: your-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000   # Specify the NodePort here
  type: NodePort

